# PC 端打包工具（在本机 Python 运行，不在 K230 上运行）
# Pack MyVisionHub project files into a self-contained MicroPython bootstrap script.
#
# 用法 / Usage:
#   python tools/pack_bootstrap.py
# 生成 dist/bootstrap_write.py：用 CanMV IDE 打开并在板子上运行一次，
# 即把下列工程文件写入 TF 卡 /sdcard/app/MyVisionHub/，全程免读卡器。
# The generated dist/bootstrap_write.py, run once from CanMV IDE, writes all
# project files to /sdcard/app/MyVisionHub/ on the TF card — no card reader needed.

import base64
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DIST_DIR = os.path.join(ROOT, "dist")
TARGET_DIR = "/sdcard/app/MyVisionHub"

# 需要部署到卡上的工程文件（相对仓库根目录，统一用 / 分隔）
# Project files to deploy (repo-relative, forward slashes)
FILES = [
    "main.py",
    "config.py",
    "output.py",
    "modules/__init__.py",
    "modules/face_det.py",
]

BOOTSTRAP_TEMPLATE = '''# MyVisionHub 引导安装脚本（由 tools/pack_bootstrap.py 自动生成，请勿手动编辑）
# Auto-generated by tools/pack_bootstrap.py — do NOT edit by hand.
#
# 用法：在 CanMV IDE 中打开本文件，点击运行一次，工程文件即写入 TF 卡 {target}
# Run once from CanMV IDE to install project files to {target} on the TF card.

import os
import ubinascii

TARGET = "{target}"
FILES = {{
{entries}
}}


def ensure_dir(path):
    """逐级创建目录，已存在则忽略 / mkdir -p equivalent."""
    cur = ""
    for part in path.strip("/").split("/"):
        cur += "/" + part
        try:
            os.mkdir(cur)
        except Exception:
            pass


def main():
    ensure_dir(TARGET)
    for rel, b64 in FILES.items():
        dest = TARGET + "/" + rel
        ensure_dir(dest.rsplit("/", 1)[0])
        data = ubinascii.a2b_base64(b64)
        with open(dest, "wb") as f:
            f.write(data)
        print("written:", dest, len(data), "bytes")
    print("MyVisionHub bootstrap done, files at", TARGET)


main()
'''


def main():
    entries = []
    for rel in FILES:
        src = os.path.join(ROOT, rel.replace("/", os.sep))
        with open(src, "rb") as f:
            b64 = base64.b64encode(f.read()).decode("ascii")
        entries.append('    "%s": "%s",' % (rel, b64))

    os.makedirs(DIST_DIR, exist_ok=True)
    out_path = os.path.join(DIST_DIR, "bootstrap_write.py")
    with open(out_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(BOOTSTRAP_TEMPLATE.format(target=TARGET_DIR, entries="\n".join(entries)))

    print("generated:", out_path)
    print("files packed:", len(FILES))
    for rel in FILES:
        print("  -", rel)


if __name__ == "__main__":
    main()
